<?php

namespace Tests\App\Rest\Actions;

use Sowl\JsonApi\Action\Resource\ShowResource;
use Sowl\JsonApi\JsonApiRequest;
use Sowl\JsonApi\JsonApiResponse;

class UserShowResource extends ShowResource
{
    public function handle(JsonApiRequest $request): JsonApiResponse
    {
        return parent::handle($request); // TODO: Change the autogenerated stub
    }
}
